version: '3.9'

services:
  todolist:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todolist
    ports:
      - "8080:8080"
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    container_name: prometheus
    volumes:
      - ./src/main/resources/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    depends_on:
      - monitoring
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
